AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gaggle-user-lambda

  Sample SAM Template for gaggle-user-lambda

Globals:
  Function:
    Timeout: 20

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: UserFunction
#      Handler: com.gaggle.lambda.GetUserByNameApproach1::handleRequest
      Handler: com.gaggle.lambda.GetUserByNameApproach2::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          DB_URL: localhost:3306
          DB_NAME: user_dev
          DB_USER: root
          DB_PASSWORD: admin
      Events:
        GetUserById:
          Type: Api
          Properties:
            Path: /user/search/{id}
            Method: get
